local LSM = LibStub("LibSharedMedia-3.0")
local AddOnName = ...
local Path = [[Interface\AddOns\]]..AddOnName..[[\media\]]
local koKR, ruRU, zhCN, zhTW, western = LSM.LOCALE_BIT_koKR, LSM.LOCALE_BIT_ruRU, LSM.LOCALE_BIT_zhCN, LSM.LOCALE_BIT_zhTW, LSM.LOCALE_BIT_western

-- local MediaType_BACKGROUND = LSM.MediaType.BACKGROUND
-- local MediaType_BORDER = LSM.MediaType.BORDER
local MediaType_FONT = LSM.MediaType.FONT
local MediaType_STATUSBAR = LSM.MediaType.STATUSBAR
local MediaType_SOUND = LSM.MediaType.SOUND

-- Fonts
LSM:Register(MediaType_FONT, 'Gotham Narrow Ultra', Path..[[Fonts\Gotham Narrow Ultra.otf]])
LSM:Register(MediaType_FONT, 'Avant Garde Bold', Path..[[Fonts\ITC Avant Garde Gothic Bold.otf]])
LSM:Register(MediaType_FONT, 'Avant Garde Medium', Path..[[Fonts\ITC Avant Garde Gothic Medium.otf]])

LSM:Register(MediaType_FONT, 'TeX Bold', Path..[[Fonts\texgyreadventor-bold.otf]])
LSM:Register(MediaType_FONT, 'TeX Bold Italic', Path..[[Fonts\texgyreadventor-bolditalic.otf]])
LSM:Register(MediaType_FONT, 'TeX Italic', Path..[[Fonts\texgyreadventor-italic.otf]])
LSM:Register(MediaType_FONT, 'TeX Regular', Path..[[Fonts\texgyreadventor-regular.otf]])

LSM:Register(MediaType_FONT, 'Naowh', Path..[[Fonts\Naowh.otf]])

-- StatusBars
LSM:Register(MediaType_STATUSBAR, 'ArrowGlow', Path..[[Textures\ArrowGlow.tga]])
LSM:Register(MediaType_STATUSBAR, 'ArrowGlowSmall', Path..[[Textures\ArrowGlowSmall.tga]])
LSM:Register(MediaType_STATUSBAR, 'Atrocity', Path..[[Textures\Atrocity.tga]])

LSM:Register(MediaType_STATUSBAR, 'BuiOnePixel', Path..[[Textures\BuiOnePixel.tga]])
LSM:Register(MediaType_STATUSBAR, 'BuiOnePixel2', Path..[[Textures\BuiOnePixel2.tga]])
LSM:Register(MediaType_STATUSBAR, 'BuiOnePixel3', Path..[[Textures\BuiOnePixel3.tga]])

LSM:Register(MediaType_STATUSBAR, 'NaowhLeft', Path..[[Textures\NaowhLeft.tga]])
LSM:Register(MediaType_STATUSBAR, 'NaowhRight', Path..[[Textures\NaowhRight.tga]])

LSM:Register(MediaType_STATUSBAR, 'ElvUI Blank', Path..[[Textures\White8x8.tga]])

LSM:Register(MediaType_STATUSBAR, 'Kait', Path..[[Textures\Kait.tga]])

-- Sounds
LSM:Register(MediaType_SOUND, "Info", Path..[[Sounds\Info.ogg]])

LSM:Register(MediaType_SOUND, "|cff0091ed1 -Naowh|r", Path..[[Sounds\1.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed2 -Naowh|r", Path..[[Sounds\2.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed3 -Naowh|r", Path..[[Sounds\3.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed4 -Naowh|r", Path..[[Sounds\4.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed5 -Naowh|r", Path..[[Sounds\5.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed6 -Naowh|r", Path..[[Sounds\6.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed7 -Naowh|r", Path..[[Sounds\7.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed8 -Naowh|r", Path..[[Sounds\8.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed9 -Naowh|r", Path..[[Sounds\9.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091ed10 -Naowh|r", Path..[[Sounds\10.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAbsorb -Naowh|r", Path..[[Sounds\Absorb.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAdd -Naowh|r", Path..[[Sounds\Add.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAdds -Naowh|r", Path..[[Sounds\Adds.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAoE -Naowh|r", Path..[[Sounds\AoE.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edAvoid -Naowh|r", Path..[[Sounds\Avoid.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBait -Naowh|r", Path..[[Sounds\Bait.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBeam -Naowh|r", Path..[[Sounds\Beam.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBehind -Naowh|r", Path..[[Sounds\Behind.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBloodlust -Naowh|r", Path..[[Sounds\Bloodlust.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBomb -Naowh|r", Path..[[Sounds\Bomb.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBreath -Naowh|r", Path..[[Sounds\Breath.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edBuff -Naowh|r", Path..[[Sounds\Buff.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edCC -Naowh|r", Path..[[Sounds\CC.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edCharge -Naowh|r", Path..[[Sounds\Charge.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edClear In -Naowh|r", Path..[[Sounds\Clear In.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edClear -Naowh|r", Path..[[Sounds\Clear.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edCollect -Naowh|r", Path..[[Sounds\Collect.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edCombat -Naowh|r", Path..[[Sounds\Combat.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDance -Naowh|r", Path..[[Sounds\Dance.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDebuff -Naowh|r", Path..[[Sounds\Debuff.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDestroy -Naowh|r", Path..[[Sounds\Destroy.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDispell -Naowh|r", Path..[[Sounds\Dispell.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDodge Inc -Naowh|r", Path..[[Sounds\Dodge Inc.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDodge -Naowh|r", Path..[[Sounds\Dodge.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edDot -Naowh|r", Path..[[Sounds\Dot.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edExternal -Naowh|r", Path..[[Sounds\External.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edFixate -Naowh|r", Path..[[Sounds\Fixate.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edFreedom -Naowh|r", Path..[[Sounds\Freedom.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edFrontal -Naowh|r", Path..[[Sounds\Frontal.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edGreen -Naowh|r", Path..[[Sounds\Green.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edHide -Naowh|r", Path..[[Sounds\Hide.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edHigh Stacks -Naowh|r", Path..[[Sounds\High Stacks.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edImmune -Naowh|r", Path..[[Sounds\Immune.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edIn -Naowh|r", Path..[[Sounds\In.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edInc -Naowh|r", Path..[[Sounds\Inc.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edInside -Naowh|r", Path..[[Sounds\Inside.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edIntermission -Naowh|r", Path..[[Sounds\Intermission.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edKick -Naowh|r", Path..[[Sounds\Kick.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edKnock -Naowh|r", Path..[[Sounds\Knock.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLeft -Naowh|r", Path..[[Sounds\Left.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLinked -Naowh|r", Path..[[Sounds\Linked.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLoS -Naowh|r", Path..[[Sounds\LoS.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLorgok_Boss Damage -Naowh|r", Path..[[Sounds\Lorgok_Boss Damage.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLorgok_Help -Naowh|r", Path..[[Sounds\Lorgok_Help.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLorgok_Oh What -Naowh|r", Path..[[Sounds\Lorgok_Oh What.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edLorgok_Yeah -Naowh|r", Path..[[Sounds\Lorgok_Yeah.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edMelee -Naowh|r", Path..[[Sounds\Melee.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edMount -Naowh|r", Path..[[Sounds\Mount.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edMove -Naowh|r", Path..[[Sounds\Move.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edNext -Naowh|r", Path..[[Sounds\Next.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edNuke -Naowh|r", Path..[[Sounds\Nuke.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edOrb -Naowh|r", Path..[[Sounds\Orb.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edOrbs -Naowh|r", Path..[[Sounds\Orbs.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edOut -Naowh|r", Path..[[Sounds\Out.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edOutrange -Naowh|r", Path..[[Sounds\Outrange.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edPersonal -Naowh|r", Path..[[Sounds\Personal.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edPot -Naowh|r", Path..[[Sounds\Pot.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edPull -Naowh|r", Path..[[Sounds\Pull.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edPush -Naowh|r", Path..[[Sounds\Push.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edRanged -Naowh|r", Path..[[Sounds\Ranged.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edReady -Naowh|r", Path..[[Sounds\Ready.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edRed -Naowh|r", Path..[[Sounds\Red.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edReflect -Naowh|r", Path..[[Sounds\Reflect.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edRight -Naowh|r", Path..[[Sounds\Right.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edRun -Naowh|r", Path..[[Sounds\Run.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSac -Naowh|r", Path..[[Sounds\Sac.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edShield -Naowh|r", Path..[[Sounds\Shield.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSoak -Naowh|r", Path..[[Sounds\Soak.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSpike -Naowh|r", Path..[[Sounds\Spike.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSpread -Naowh|r", Path..[[Sounds\Spread.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edStack -Naowh|r", Path..[[Sounds\Stack.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edStop -Naowh|r", Path..[[Sounds\Stop.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edStop Cast -Naowh|r", Path..[[Sounds\Stop Cast.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edSwitch -Naowh|r", Path..[[Sounds\Switch.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edTaunt -Naowh|r", Path..[[Sounds\Taunt.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edTotem -Naowh|r", Path..[[Sounds\Totem.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edTrap -Naowh|r", Path..[[Sounds\Trap.ogg]])
LSM:Register(MediaType_SOUND, "|cff0091edTurn -Naowh|r", Path..[[Sounds\Turn.ogg]])

-- LSM:Register(MediaType_STATUSBAR, 'NaowhRing1', Path..[[Textures\NaowhRing1.tga]])
-- LSM:Register(MediaType_STATUSBAR, 'NaowhRing2', Path..[[Textures\NaowhRing2.tga]])
-- LSM:Register(MediaType_STATUSBAR, 'NaowhRing3', Path..[[Textures\NaowhRing3.tga]])
-- LSM:Register(MediaType_STATUSBAR, 'NaowhRing4', Path..[[Textures\NaowhRing4.tga]])
-- LSM:Register(MediaType_STATUSBAR, 'NaowhRing5', Path..[[Textures\NaowhRing5.tga]])
-- LSM:Register(MediaType_STATUSBAR, 'NaowhRing6', Path..[[Textures\NaowhRing6.tga]])

